
export const data = [
  {
    id: 1,
    title: "p-001 velo",
    workId: "p001",
    subTitle: 'A BATTERY POWERED LIGHT VEHICLE INTENDED FOR SHORT TO MEDIUM DISTANCE COMMERCIAL USE',
    services: [1,2,3,4],
    client: "Personal Project",
    timeline: 2,
    year: 2023,
    images: '/images/works/detail/1/hero.png',
    discover: {
      paragraph: '“Rengklek” is the problem for increasing risk the the problem modification of their motorbike',
      subParagraph: '“Rengklek” is the problem for increasing risk the the problem modification of their motorbike',
      images: null,
    },
    define: {
      paragraph: '“Rengklek” is the problem for increasing risk the the problem modification of their motorbike',
      subParagraph: '“Rengklek” is the problem for increasing risk the the problem modification of their motorbike',
      images: '/images/works/detail/1/define.png',
    },
    design: {
      paragraph: '“Rengklek” is the problem for increasing risk the the problem modification of their motorbike',
      subParagraph: '“Rengklek” is the problem for increasing risk the the problem modification of their motorbike',
      images: '/images/works/detail/1/design.png',
    },
    deliver: {
      paragraph: '“Rengklek” is the problem for increasing risk the the problem modification of their motorbike',
      subParagraph: '“Rengklek” is the problem for increasing risk the the problem modification of their motorbike',
      images: '/images/works/detail/1/deliver.png',
    },
  },
  {
    id: 2,
    title: "Nike Blueno",
    workId: "p002",
    subTitle: 'When Retro Meets Modern Performance',
    services: [1,2,3,4],
    client: "Personal Project",
    timeline: 2,
    year: 2023,
    images: '/images/works/detail/2/hero.png',
    discover: {
      paragraph: 'Nike Blueno are designed by merging the visual language of classic basketball sneakers with modern performance aesthetics.',
      subParagraph: 'The design draws inspiration from the bold silhouettes and layered constructions commonly found in retro basketball footwear from the late 90s and early 2000s, while integrating contemporary sculptural forms and streamlined detailing.',
      images: null,
    },
    define: {
      paragraph: 'The upper features dynamic flowing panels that create a sense of motion and speed, echoing the expressive overlays typical of retro basketball shoes. These layered structures not only build a strong visual identity but also emphasize support and foot containment, which are essential elements in basketball footwear design.',
      subParagraph: null,
      images: '/images/works/detail/2/define.png',
    },
    design: {
      paragraph: 'In contrast, the midsole introduces a more modern approach. Its sculpted geometry and aerodynamic lines reflect current trends in performance footwear, where form and function merge into a more fluid and futuristic structure. The aggressive curves and flowing ridges visually communicate energy, impact absorption, and responsiveness during play.',
      subParagraph: null,
      images: '/images/works/detail/2/design.png',
    },
    deliver: {
      paragraph: 'Through this combination of retro layering and contemporary sculptural form, Blueno aims to create a basketball shoe that feels nostalgic yet progressive—bridging past basketball culture with modern footwear innovation.',
      subParagraph: 'Here is the lateral and median look from aside.',
      images: '/images/works/detail/2/deliver.png',
    },
  },
  {
    id: 1,
    title: "ACQUO",
    workId: "p003",
    subTitle: 'This project explores the intersection between functional homeware and architectural form.',
    services: [1,2,3,4],
    client: "Personal Project",
    timeline: 2,
    year: 2023,
    images: '/images/works/detail/3/hero.png',
    discover: {
      paragraph: 'The design moves beyond the conventional language of water pitchers by introducing bold geometric structures and strong visual contrast, transforming a simple household object into a sculptural centerpiece.',
      subParagraph: null,
      images: null,
    },
    define: {
      paragraph: 'The form is inspired by architectural massing and structural balance. Instead of relying on soft organic curves commonly found in pitchers, this design emphasizes clean lines, defined edges, and confident proportions. The result is a pitcher that feels structured and intentional—almost like a small architectural object placed on a dining table.',
      subParagraph: null,
      images: '/images/works/detail/3/define.png',
    },
    design: {
      paragraph: 'A key element of the design is the contrast between solid geometry and visual lightness. The composition balances volume and negative space, allowing the object to feel both stable and visually dynamic. This balance ensures that the pitcher maintains practicality for everyday use while also functioning as a design statement.',
      subParagraph: null,
      images: '/images/works/detail/3/design.png',
    },
    deliver: {
      paragraph: 'This project aims to demonstrate how everyday objects can be elevated through thoughtful form exploration. The pitcher is not only designed to serve water, but also to enhance spatial aesthetics, bringing a sense of modern architecture into the domestic environment.',
      subParagraph: null,
      images: '/images/works/detail/3/deliver.png',
    },
  },
];