import { Hanken_Grotesk } from "next/font/google";
import "./globals.css";

const hanken = Hanken_Grotesk({
  subsets: ["latin"],
  variable: "--font-hanken-grotesk",
  display: "swap",
});

export const metadata = {
  title: "IOU Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={hanken.variable}>
      <body className="min-h-screen bg-[#F5F5F5] font-hanken">
        {children}
      </body>
    </html>
  );
}
