import { Hanken_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";

const hanken = Hanken_Grotesk({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

export const metadata = {
  title: "IOU Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={hanken.variable}>
      <body
        className="min-h-screen bg-background font-sans antialiased"
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
